<%@ Page Title="" Language="C#" MasterPageFile="~/StitchQueueMaster.Master" AutoEventWireup="true" CodeBehind="PrivacyPolicy.aspx.cs" Inherits="StitchQueue.PrivacyPolicy" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <style type="text/css">
 .privacy_text
  {
    font-size: 16px;
    font-family: 'Montserrat', sans-serif;
    line-height: 30px;
  }
 .sub_ul li
  {
    font-size: 16px;
    font-family: 'Montserrat', sans-serif;
    line-height: 30px;
    
  }
  .page_h4
  {
    font-family: 'Montserrat', sans-serif;
    background:#E02051;
    color: #fff;
    padding: 8px;
    margin-top: 10px;
    margin-bottom: 10px;
  }
</style>


<br><br>

<section id="privacypolicy">
    <div class="container-fluid">
      <div class="row wow fadeInUp" style="visibility: visible; animation-name: none;">
         <p class="header_text">Privacy Policy <br><img src="./images/hr_line2.png" alt="heding image" width="100"></p>
       </div> 
        <div class="container">

          <ol class="sub_ul">
            <li>We firmly believe in your privacy and the security of your personal information. We do not rent, sell or distribute our customer base or newsletter e-mails to anyone.</li>
            <li>Via E-mail, we only send our newsletter to email addresses that have opted in, and they may opt out at any time. If you place an order with us, we send email messages pertaining to your order. We do not sell your email address to other parties.</li>
            <li>We collect your personal information when you provide it to us as you place your order, including your name, shipping and billing address, credit card number, and email address. We use this information to process your order, provide you with support, and update you on your order. We do not sell your personal information to other parties.</li>
            <li>We collect non-personal information from you, including your browser type, the URL of the previous website you visited, your ISP, operating system, etc. This information is anonymous and is collected by almost all sites that you visit. We use this information, which does not identify individual users, to analyze trends, to administer the site, to track users' movements around the site and gather demographic information about our user base as a whole.</li>
            <li>Like almost all e-commerce websites, we use cookies. Our cookies don't store any of your personal information, but they do allow us to do things like keep items in your shopping cart during your visit or provide you with a more personalized user experience. We may use selected third parties for marketing and analysis purposes. This anonymous information is collected through the use of a pixel tag, which is industry standard technology used by most major websites. We feel that the use of 3rd party services such as this improves your online experience because they allow you to see ads that will be more likely to be something you are interested in.</li>
            <li>We maintain best practices to protect your information, which includes appropriate physical as well as electronic security measures. We use 128bit Secure Socket Layer (SSL) technology to encrypt all of your private information when placing an order, which ensures that no one else can read this information.</li>
            <li>Although we have taken all kinds of security measures for the protection of personal information, we cannot guarantee complete protection. You provide all personal information at your own risk.</li>
          </ol>

        <br>
       <h4 class="page_h4"><strong>GRIEVANCE</strong></h4>

       <ol class="sub_ul">
         <li>Any grievances you have by way of use of the website can be addressed to the ‘Customer Care’ by way of email to support@stitchq.com.</li>
         <li>The ‘Customer Care’ shall thereafter consider the same and provide a response within one month of the date of such complaint/ grievance.</li>
         <li>This electronic record is generated by a computer system and does not require any physical or digital signatures.</li>
       </ol>
 
        </div>
        
    </div>
</section>


<br><br>
</asp:Content>
